export const taskPlan: Record<string, string[]> = {
  'HU-01': ['Definir niveles y puntos interactivos del recorrido', 'Mostrar el avance escolar dentro del mapa'],
  'HU-02': ['Validar si el nivel elegido está disponible', 'Abrir la lección asociada al nivel'],
  'HU-03': ['Guardar el nivel y la lección actuales', 'Restaurar la ruta al volver a iniciar sesión'],
  'HU-04': ['Ordenar las unidades según la secuencia curricular', 'Vincular cada unidad con sus niveles de aprendizaje'],
  'HU-05': ['Definir los campos para crear una ruta personalizada', 'Guardar la ruta y asociarla a materiales docentes'],
  'HU-06': ['Permitir reordenar módulos con arrastrar y soltar', 'Guardar y mostrar la nueva secuencia'],
  'HU-07': ['Validar archivos PDF y PPT y enlaces externos', 'Asociar cada material con un nodo de la ruta'],
  'HU-08': ['Agregar estados publicada y pausada a la ruta', 'Restringir el acceso de estudiantes según el estado'],
  'HU-09': ['Buscar rutas por nombre de materia', 'Mostrar resultados relevantes al escribir'],
  'HU-10': ['Agregar filtros por grado escolar', 'Actualizar los resultados según el grado elegido'],
  'HU-11': ['Generar y validar códigos de acceso a rutas', 'Vincular al estudiante con la ruta de su aula'],
  'HU-12': ['Habilitar descarga de materiales del nodo', 'Preparar los recursos para consulta sin conexión'],
  'HU-13': ['Registrar fechas de unidades y evaluaciones', 'Mostrar el calendario junto a la ruta del aula'],
  'HU-14': ['Programar recordatorios desde las fechas de evaluación', 'Evitar avisos duplicados para una misma fecha'],
  'HU-15': ['Definir modos de ayuda del tutor para el aula', 'Aplicar el modo elegido en las interacciones del alumno'],
  'HU-16': ['Detectar competencias con bajo rendimiento', 'Vincular actividades MINEDU de refuerzo al nodo correspondiente'],
  'HU-17': ['Resumir resultados por estudiante y unidad', 'Destacar competencias que requieren atención docente'],
  'HU-18': ['Calcular promedios por unidad curricular', 'Presentar calificaciones en una tabla legible'],
  'HU-19': ['Agregar un filtro de estudiante al reporte', 'Actualizar indicadores al elegir un alumno'],
  'HU-20': ['Identificar estudiantes que requieren refuerzo', 'Asignar actividades distintas según la necesidad detectada'],
  'HU-21': ['Definir preguntas a partir del tema estudiado', 'Generar y revisar un cuestionario breve con IA'],
  'HU-22': ['Crear tarjetas con pregunta y respuesta', 'Implementar giro y gesto táctil para revisar cada tarjeta'],
  'HU-23': ['Resumir el contenido en una infografía adecuada al grado', 'Mostrar el recurso visual junto al tema correspondiente'],
  'HU-24': ['Adaptar controles táctiles al tamaño de pantalla', 'Revisar que el contenido no requiera desplazamiento lateral'],
  'HU-25': ['Permitir elegir metas y tipos de recordatorio', 'Enviar avisos solo de acuerdo con las preferencias guardadas'],
  'HU-26': ['Guardar la hora diaria elegida por el estudiante', 'Programar el recordatorio en la hora local configurada'],
  'HU-27': ['Detectar cuándo la racha está por interrumpirse', 'Enviar un aviso motivacional antes del cierre del día'],
  'HU-28': ['Detectar nuevas publicaciones del docente', 'Avisar al aula sobre materiales o evaluaciones habilitados'],
  'HU-29': ['Definir puntos por actividad completada', 'Otorgar y mostrar medallas al alcanzar sus condiciones'],
  'HU-30': ['Calcular días consecutivos con actividad', 'Mostrar la racha junto al avatar de Rupi'],
  'HU-31': ['Definir requisitos para desbloquear accesorios', 'Permitir personalizar la mascota con los elementos obtenidos'],
  'HU-32': ['Calcular logros visibles para el aula', 'Presentar posiciones sin exponer datos innecesarios del alumno'],
  'HU-33': ['Contabilizar lecciones completadas por estudiante', 'Mostrar el total actualizado en el panel principal'],
  'HU-34': ['Elegir la métrica que representa el avance diario', 'Actualizar el indicador al completar una actividad'],
  'HU-35': ['Confirmar con el equipo si se conserva o retira esta historia duplicada'],
  'HU-36': ['Guardar los puntajes diarios del estudiante', 'Comparar el resultado actual con el día anterior'],
  'HU-37': ['Ajustar las pistas al nivel de aprendizaje del alumno', 'Explicar errores sin revelar directamente la respuesta'],
  'HU-38': ['Relacionar conceptos con ejemplos cotidianos', 'Mostrar ejemplos pertinentes a la edad y al contexto peruano'],
  'HU-39': ['Integrar lectura por voz en consignas y explicaciones', 'Agregar controles para iniciar, pausar y repetir el audio'],
  'HU-40': ['Definir retos diarios de lógica y comprensión lectora', 'Contextualizar los retos con situaciones peruanas'],
  'HU-41': ['Crear operaciones para registrar, editar y desactivar cuentas', 'Conservar un registro consistente de docentes y alumnos'],
  'HU-42': ['Definir permisos por rol y módulo', 'Restringir consultas y acciones según el rol asignado'],
  'HU-43': ['Definir cómo resolver sesiones abiertas en varios dispositivos', 'Sincronizar el estado de sesión entre web y móvil'],
  'HU-44': ['Crear el flujo autorizado para restablecer credenciales', 'Registrar desbloqueos de cuentas institucionales'],
  'HU-45': ['Recolectar disponibilidad y tiempos de respuesta', 'Mostrar alertas de salud antes de afectar las clases'],
  'HU-46': ['Registrar eventos de sincronización entre clientes', 'Detectar diferencias entre lecciones y puntajes sincronizados'],
  'HU-47': ['Definir umbrales de caída para IA y base de datos', 'Notificar al responsable cuando se supere un umbral'],
  'HU-48': ['Consolidar métricas de disponibilidad y errores', 'Mostrar tendencias técnicas en un tablero central'],
  'HU-49': ['Modelar grados, áreas y competencias curriculares', 'Validar que cada ruta use elementos del catálogo oficial'],
  'HU-50': ['Registrar metas y estándares por unidad', 'Permitir corregirlos conservando su relación curricular'],
  'HU-51': ['Registrar la versión y vigencia de cada correspondencia', 'Actualizar rutas afectadas por cambios ministeriales'],
  'HU-52': ['Configurar bimestres y trimestres por calendario', 'Aplicar los periodos seleccionados a la planificación'],
  'HU-53': ['Definir reglas de evaluación seguras para menores', 'Probar respuestas de IA con casos de lenguaje inapropiado'],
  'HU-54': ['Registrar interacciones necesarias para auditoría', 'Permitir búsquedas de revisión con acceso restringido'],
  'HU-55': ['Validar instrucciones antes de enviarlas al modelo', 'Bloquear intentos de alterar las reglas de seguridad'],
  'HU-56': ['Mantener una lista configurable de expresiones bloqueadas', 'Revisar mensajes y evitar mostrar contenido ofensivo'],
  'HU-57': ['Definir frecuencia y horario de los respaldos', 'Comprobar que una copia pueda restaurarse correctamente'],
  'HU-58': ['Configurar intentos permitidos y duración del bloqueo', 'Aplicar límites de acceso en web y móvil'],
  'HU-59': ['Preparar escenarios de recuperación en un entorno aislado', 'Medir la integridad y el tiempo de restauración'],
  'HU-60': ['Definir segundo factor para cuentas docentes y administrativas', 'Proteger el inicio de sesión con el segundo factor obligatorio'],
}
